# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160109_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompost',
            name='timezone',
            field=models.CharField(blank=True, default=b'UTC', max_length=255),
        ),
    ]
