# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0004_auto_20160109_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('blog', 'slug')]),
        ),
    ]
