# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0005_auto_20160109_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='backend_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'html', 'HTML'), (b'plain', 'Plain'), (b'markdown', 'Markdown'), (b'restructuredtext', 'Restructured Text')], default=b'markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='timezone',
            field=models.CharField(blank=True, default=b'UTC', max_length=255),
        ),
    ]
