# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0006_auto_20160311_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'html', 'HTML'), (b'plain', 'Plain'), (b'markdown', 'Markdown')], default=b'markdown', max_length=30),
        ),
    ]
