# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0007_auto_20160323_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sync',
            field=models.BooleanField(default=True),
        ),
    ]
