# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0008_blog_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sync',
            field=models.BooleanField(default=True, help_text=b"This blog should sync using it's selected backend"),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_markup_type',
            field=models.CharField(choices=[(b'', b'--'), (b'html', 'HTML'), (b'plain', 'Plain'), (b'markdown', 'Markdown'), (b'restructuredtext', 'Restructured Text')], default=b'markdown', max_length=30),
        ),
    ]
