# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stardate', '0009_auto_20170301_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='social_auth',
        ),
    ]
